SmartSync/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'homepage#index'

  get  'login'  => 'sessions#new', as: :login
  post 'login'  => 'sessions#create'
  get 'logout'  => 'sessions#destroy', as: :logout
  # get 'oauth' => 'google#oauth'
  # get 'oauth/redirect' => 'google#token'
  # get 'oauth/profile/update' => 'google#profile_edit', as: :oauth_update_profile
  # post 'oauth/profile' => 'google#profile_update'

  get 'auth/:provider/callback', to: 'sessions#oauth', as: :oauth
  get 'auth/failure', to: redirect('/')

  resources :sessions, only: [:oauth, :new, :create, :destroy]

  resources :users do

    member do
      get 'homes'
      get 'rooms'
      get 'devices'
    end

  end

  resources :homes do
    resources :rooms do
      resources :devices
    end
  end
end

SmartSync/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :properties
  has_many :homes, through: :properties, dependent: :destroy
  has_many :rooms, through: :homes, source: :properties

  has_many :user_devices
  has_many :devices, through: :user_devices

  validates :email, {
    :uniqueness => {:case_sensitive => false},
    :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  }

  validates :password, :presence => true, length: {minimum: 6}, confirmation: true

  devise :omniauthable, :omniauth_providers => [:google_oauth2]

## User Model - Create from Oauth
###########################################

def self.from_oauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end

### User Model - Class Methods
###########################################

def keys
  [:name, :first_name, :last_name, :email, :cell_phone, :password]
end

def counts
  user = User.find(session[:user_id])
  return { homes: user.homes,
   rooms: user.rooms,
   devices: user.devices }
 end

end

SmartSync/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end

SmartSync/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      set_current_user(user)
      redirect_to user
    else
      render 'new'
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end

  end

  def show
    @user = User.find(params[:id])
    @counts = counts
  end

  def homes
    @homes = User.find(params[:id]).homes
  end

  def rooms
    @homes = User.find(session[:user_id]).homes
  end

  def devices
    @homes = User.find(session[:user_id]).homes
  end

  private

  def user_params
    params.require(:user).permit(:name, :first_name, :last_name, :email, :password, :password_confirmation)
  end

  def counts
    homes = User.find(session[:user_id]).homes
    home_count = homes.length
    room_count = 0
    device_count = 0
    homes.each do |home|
      room_count += home.rooms.count
      device_count += home.devices.count
    end

    return {  homes: home_count,
              rooms: room_count,
              devices: device_count  }
  end

  #  def set_current_user(user)
  #   session[:user_id] = user.id
  #   @current_user = user
  # end

end

SmartSync/app/helpers/users_helper.rb
module UsersHelper
end

SmartSync/app/views/users/devices.html.erb
<h1>Devices</h1>

<% @homes.each do |home| %>

  <hr><h3>Property: <%= link_to home.name, home %> - <%= home.city %>, <%= home.state %></h3>

  <% @rooms = home.rooms %>
  <% @rooms.each do |room| %>

    <h4>&nbsp;&nbsp;&nbsp;Room: <%= link_to room.name, [room.home, room] %> - <%= room.description %></h4>

    <% @devices = room.devices %>
    <% @devices.each do |device| %>

      <h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Device: <%= link_to device.name, [device.home, device.room, device] %> - <small><%= device.description %></small></h5>
    <% end %>
  <% end %>
<% end %>

SmartSync/app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="page-header">
    <h1><i class="fa fa-user fa-5x text-primary"></i> User <small>Update Information</small></h1>
  </div>
</div>


<!-- /////////////////// Insert Body Content Here /////////////////// -->
<div class='container-body'>
  <%= form_for @user, url: {action: "update"} do |f| %><!-- Begin | Update Form -->
  <fieldset>

    <div class="col-md-7">
      <legend>
        <h4><i class="fa fa-chevron-right fa-1x"></i> Update Information:<small>  Fill in the required fields.</small></h4>
      </legend>

      <div>
        <label class="small" for="firstname">First Name (Required)</label>
        <%= f.text_field :first_name %>
      </div><br>

      <div>
        <label class="small" for="register_lastname">Last Name (Required)</label>
        <%= f.text_field :last_name %>
      </div><br>

      <div>
        <label class="small" for="register_email">Email Address (Required)</label>
        <%= f.text_field :email %>
      </div><br>

      <div>
        <label class="small" for="register_password">Password (Required)</label>
        <%= f.password_field :password %>
        <%= f.password_field :password_confirmation %>
      </div><br>

      <%= button_tag(type: 'submit', class: 'btn btn-lg btn-social btn-primary') do %>
      <i class="fa fa-lock"></i> Register
      <% end %>
    </div>
  </fieldset>
  <% end %><!-- End | Register Form -->
</div>

SmartSync/app/views/users/homes.html.erb
<h1>Users#homes</h1>
<p>Find me in app/views/users/homes.html.erb</p>

SmartSync/app/views/users/new.html.erb
<div class="container-fluid">
    <div class="page-header">
        <h1><i class="fa fa-user fa-5x text-primary"></i> User <small>Registration</small></h1>
    </div>
</div>


<!-- /////////////////// Insert Body Content Here /////////////////// -->
<div class='container-body'>
    <%= form_for @user, url: {action: "create"} do |f| %><!-- Begin | Register Form -->
    <fieldset>

        <div class="col-md-7">
            <legend>
                <h4><i class="fa fa-chevron-right fa-1x"></i> Registration:<small>  Fill in the required fields.</small></h4>
            </legend>

            <div>
                <label class="small" for="firstname">First Name (Required)</label>
                <%= f.text_field :first_name %>
            </div><br>

            <div>
                <label class="small" for="register_lastname">Last Name (Required)</label>
                <%= f.text_field :last_name %>
            </div><br>

            <div>
                <label class="small" for="register_email">Email Address (Required)</label>
                <%= f.text_field :email %>
            </div><br>

            <div>
                <label class="small" for="register_password">Password (Required)</label>
                <%= f.password_field :password %>
                <%= f.password_field :password_confirmation %>
            </div><br>

            <%= button_tag(type: 'submit', class: 'btn btn-lg btn-social btn-primary') do %>
            <i class="fa fa-lock"></i> Register
            <% end %>
        </div>
    </fieldset>
    <% end %><!-- End | Register Form -->
</div>

SmartSync/app/views/users/profile.erb
<div class="container-fluid">
    <div class="page-header">
        <div class="pull-right">
            <% unless api_status == "Online" %>
            <%= image_tag("/icons/active/il.png", class: "logo-image-mp img-responsive center-block") %>
            <% end %>
        </div>
        <% if !@config.user.picture.nil? %>
        <h1><img class="img-thumbnail img-circle" width="100" height="100" src="<%= @config.user.picture %>" alt="User Profile Picture"> User <small>Profile</small></h1>
        <% else %>
        <h1><i class="fa fa-user fa-5x text-primary"></i> User <small>Profile</small></h1>
        <% end %>

        <div class="login-alert-partial">
            <%= erb :'partials/_login_alert', :layout => false if logged_in? %>

        </div>

    </div>
</div>

<!-- /////////////////////////////////// Insert Body Content Here /////////////////////////////////// -->
<div class='container-body'>

    <!-- Boxes -->  <div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-home fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @counts[:homes] %></div>
                        <div>Properties</div>
                    </div>
                </div>
            </div>
            <a href="/user/<%= @config.user.id %>/home/new">
                <div class="panel-footer">
                    <span class="pull-left">New Property</span>
                    <span class="pull-right"><i class="fa fa-plus"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="/user/<%= @config.user.id %>/home/show">
                <div class="panel-footer">
                    <span class="pull-left">View Properties</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-hotel fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @counts[:rooms] %></div>
                        <div>Rooms</div>
                    </div>
                </div>
            </div>
            <a href="/user/<%= @config.user.id %>/room/new">
                <div class="panel-footer">
                    <span class="pull-left">New Room</span>
                    <span class="pull-right"><i class="fa fa-plus"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="/user/<%= @config.user.id %>/room/show">
                <div class="panel-footer">
                    <span class="pull-left">View Rooms</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-lightbulb-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><%= @counts[:devices] %></div>
                        <div>Devices</div>
                    </div>
                </div>
            </div>
            <a href="/user/<%= @config.user.id %>/device/new/form">
                <div class="panel-footer">
                    <span class="pull-left">New Device</span>
                    <span class="pull-right"><i class="fa fa-plus"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="/user/<%= @config.user.id %>/device/show">
                <div class="panel-footer">
                    <span class="pull-left">View Devices</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="/user/<%= @config.user.id %>/device/show/favorites">
                <div class="panel-footer">
                    <span class="pull-left">Favorite Devices</span>
                    <span class="pull-right"><i class="fa fa-thumbs-up"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-calendar fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">0</div>
                        <div>Schedules</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
</div>
<!-- /////////////////////////////////// Insert Body Content Here /////////////////////////////////// -->

</div>

SmartSync/app/views/users/rooms.html.erb
<h1>Rooms</h1>

<% @homes.each do |home| %>

  <p>Property: <%= link_to home.name, home %> - <%= home.city %>, <%= home.state %></p>

  <% @rooms = home.rooms %>
  <% @rooms.each do |room| %>
    <p>Rooms: <%= link_to room.name, [room.home, room] %> - <%= room.description %></p>
  <% end %>
<% end %>

SmartSync/app/views/users/show.html.erb
<div class="container-fluid">
  <div class="page-header">
    <div class="pull-right">
      <% if session[:user_id] %>
      <%= image_tag("/icons/active/il.png", class: "logo-image-mp img-responsive center-block") %>
      <% end %>
    </div>

    <h1><i class="fa fa-user fa-5x text-primary"></i> User <small>Profile</small></h1>


  </div>
</div>

<!-- /////////////////////////////////// Insert Body Content Here /////////////////////////////////// -->
<div class='container-body'>

  <!-- Boxes -->  <div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-home fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @counts[:homes] %></div>
            <div>Properties</div>
          </div>
        </div>
      </div>

      <%= link_to(new_home_path) do %>
      <div class="panel-footer">
        <span class="pull-left">New Property</span>
        <span class="pull-right"><i class="fa fa-plus"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

      <%= link_to(devices_user_path) do %>
      <div class="panel-footer">
        <span class="pull-left">View Properties</span>
        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-hotel fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @counts[:rooms] %></div>
            <div>Rooms</div>
          </div>
        </div>
      </div>

      <%= link_to("/homes/#{params[:id]}/rooms/new") do %>
      <div class="panel-footer">
        <span class="pull-left">New Room</span>
        <span class="pull-right"><i class="fa fa-plus"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

      <%= link_to("/homes/#{params[:home_id]}/rooms") do %>
      <div class="panel-footer">
        <span class="pull-left">View Rooms</span>
        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-lightbulb-o fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @counts[:devices] %></div>
            <div>Devices</div>
          </div>
        </div>
      </div>

      <%= link_to("/homes/#{params[:home_id]}/rooms/#{params[:id]}/devices/new") do %>
      <div class="panel-footer">
        <span class="pull-left">New Device</span>
        <span class="pull-right"><i class="fa fa-plus"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

      <%= link_to("/homes/#{params[:home_id]}/rooms/#{params[:room_id]}/devices") do %>
      <div class="panel-footer">
        <span class="pull-left">View Devices</span>
        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

      <%= link_to("/user/#{params[:home_id]}/rooms/#{params[:room_id]}/devices") do %>
      <div class="panel-footer">
        <span class="pull-left">Favorite Devices</span>
        <span class="pull-right"><i class="fa fa-thumbs-up"></i></span>
        <div class="clearfix"></div>
      </div>
      <% end %>

    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-calendar fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">0</div>
            <div>Schedules</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>
</div>
<!-- /////////////////////////////////// Insert Body Content Here /////////////////////////////////// -->

</div>