SmartSync/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'homepage#index'

  get  'login'  => 'sessions#new', as: :login
  post 'login'  => 'sessions#create'
  get 'logout'  => 'sessions#destroy', as: :logout
  # get 'oauth' => 'google#oauth'
  # get 'oauth/redirect' => 'google#token'
  # get 'oauth/profile/update' => 'google#profile_edit', as: :oauth_update_profile
  # post 'oauth/profile' => 'google#profile_update'

  get 'auth/:provider/callback', to: 'sessions#oauth', as: :oauth
  get 'auth/failure', to: redirect('/')

  resources :sessions, only: [:oauth, :new, :create, :destroy]

  resources :users do

    member do
      get 'homes'
      get 'rooms'
      get 'devices'
    end

  end

  resources :homes do
    resources :rooms do
      resources :devices
    end
  end
end

SmartSync/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    render 'index', :layout => false
  end
end

SmartSync/app/helpers/homepage_helper.rb
module HomepageHelper
end

SmartSync/app/views/homepage/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmartSync</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="container-fluid">
      <div class="container">

        <div class="page-header">
          <%= image_tag("logo/home-logo-with-tag-large.png", class: "img-responsive center-block front-page-logo") %>
        </div>

        <div class="text-center">

          <%= link_to(oauth_path, class: 'btn btn-lg btn-social btn-google custom-login-buttons') do %>
          <i class="fa fa-google-plus"></i> Sign in with Google
          <% end %>

          <%= link_to(login_path, class: 'btn btn-lg btn-social btn-primary custom-login-buttons') do %>
          <i class="fa fa-fw fa-lock"></i> Login
          <% end %>

          <%= link_to(new_user_path, class: 'btn btn-lg btn-social btn-primary custom-login-buttons') do %>
          <i class="fa fa-lock"></i> Register
          <% end %>

        </div>
      </div>
    </div>
  </div>
</body>
</html>