SmartSync/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'homepage#index'

  get  'login'  => 'sessions#new', as: :login
  post 'login'  => 'sessions#create'
  get 'logout'  => 'sessions#destroy', as: :logout
  # get 'oauth' => 'google#oauth'
  # get 'oauth/redirect' => 'google#token'
  # get 'oauth/profile/update' => 'google#profile_edit', as: :oauth_update_profile
  # post 'oauth/profile' => 'google#profile_update'

  get 'auth/:provider/callback', to: 'sessions#oauth', as: :oauth
  get 'auth/failure', to: redirect('/')

  resources :sessions, only: [:oauth, :new, :create, :destroy]

  resources :users do

    member do
      get 'homes'
      get 'rooms'
      get 'devices'
    end

  end

  resources :homes do
    resources :rooms do
      resources :devices
    end
  end
end

SmartSync/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmartSync</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="icon-bar">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"> Smart Sync</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li><a href="#"> <span class="label label-default"> </span></a></li>
                        <li><a href="#"> <span class="label label-primary"> </span></a></li>
                        <li><a href="#"> <span class="label label-success"> </span></a></li>
                        <li><a href="#"> <span class="label label-info"> </span></a></li>
                        <li><a href="#"> <span class="label label-warning"> </span></a></li>
                        <li class="divider"></li>
                        <li><a href="#">View All</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= "User" %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <% if logged_in? %>
                        <li>
                            <%= link_to(user_path) do %>
                            <i class="fa fa-fw fa-user"></i> View Profile
                            <% end %>
                        </li>

                        <li>
                            <%= link_to(edit_user_path) do %>
                            <i class="fa fa-fw fa-wrench"></i> Update Profile
                            <% end %>
                        </li>

                        <li>
                            <%= link_to(logout_path) do %>
                            <i class="fa fa-fw fa-power-off"></i> Log Out
                            <% end %>
                        </li>

                        <% end %>

                        <% unless logged_in? %>

                        <li>
                            <%= link_to(login_path) do %>
                            <i class="fa fa-fw fa-lock"></i> Login
                            <% end %>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <%= link_to(new_user_path) do %>
                            <i class="fa fa-fw fa-user-plus"></i> Register
                            <% end %>
                        </li>

                        <% end %>

                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="/"><i class="fa fa-fw fa-lock"></i> Home</a>
                    </li>
                    <li>
                        <a href="javascript:parent.history.back();"><i class="fa fa-fw fa-lock"></i> Back</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#users"><i class="fa fa-fw fa-user"></i> User<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="users" class="collapse">
                            <li>

                                <% if logged_in? %>

                                <%= link_to(user_path) do %>
                                <i class="fa fa-fw fa-user"></i> View Profile
                                <% end %>

                                <%= link_to(edit_user_path) do %>
                                <i class="fa fa-fw fa-wrench"></i> Update Profile
                                <% end %>

                                <%= link_to(logout_path) do %>
                                <i class="fa fa-fw fa-power-off"></i> Log Out
                                <% end %>

                                <% else %>

                                <%= link_to(login_path) do %>
                                <i class="fa fa-fw fa-lock"></i> Login
                                <% end %>

                                <%= link_to(new_user_path) do %>
                                <i class="fa fa-fw fa-user-plus"></i> Register
                                <% end %>

                                <% end %>

                            </li>
                        </ul>
                    </li>

                    <% if logged_in? %>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#properties"><i class="fa fa-fw fa-home"></i> Properties<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="properties" class="collapse">
                            <li><a href="/user/<%= @user_id %>/home/show"><i class="fa fa-fw fa-home"></i> - List All Homes</a></li>
                            <li><a href="/user/<%= @user_id %>/room/show"><i class="fa fa-fw fa-hotel"></i> - List All Rooms</a></li>
                            <li><a href="/user/<%= @user_id %>/device/show"><i class="fa fa-fw fa-lightbulb-o"></i> - List All Devices</a></li>
                            <li><a href="#"><i class="fa fa-fw fa-calendar"></i> - View Schedules</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#schedules"><i class="fa fa-fw fa-calendar"></i> Schedules<i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="schedules" class="collapse">
                            <li><a href="#"><i class="fa fa-fw fa-calendar"></i> - View Schedules</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#Insteon"><%= image_tag("icons/active/il.png", class: "logo-image-mp")%></a>
                        <ul id="Insteon" class="collapse">
                            <li><a href="/oauth/insteon"><i class="fa fa-fw fa-lock"></i> - Login</a></li>
                            <li><a href="#"><i class="fa fa-fw fa-user"></i> - Modify Account</a></li>
                        </ul>
                    </li>
                    <% end %>
                </ul>
            </div>
        </nav>

        <div id="page-wrapper">
            <div class="container-fluid">
                <!-- /////////////////////////////////// Insert Body Content Here /////////////////////////////////// -->
                <!-- <div class='container-body'> -->
                    <%= yield %>
                <!-- </div> -->
                <!-- /////////////////////////////////// Insert Body Content Here /////////////////////////////////// -->
            </div>
        </div>
    </div>
</body>
</html>